name       : conky-manager
version    : 2.4
release    : 18
source     :
    - https://launchpad.net/~teejee2008/+archive/ubuntu/ppa/+files/conky-manager_2.4~136~ubuntu15.04.1.tar.xz : ee93d8661f28ae7823fa88a20f7ebf19d82eeecb04e55bf83fe9dea08d4929c0
license    : GPL-3.0-or-later
component  : system.utils
summary    : Conky Manager
description: |
    Conky Manager is a graphical front-end for managing Conky config files. It provides options to start/stop, browse and edit Conky themes installed on the system.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ImageMagick)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
    - vala
rundeps    :
    - conky
    - imagemagick
    - p7zip
    - rsync
build      : |
    %patch -Np0 < $pkgfiles/makefile-roundup.patch
    %make -j1
install    : |
    %make_install
