name       : conky-manager
version    : 2.3.3
release    : 1
source     :
    - https://launchpad.net/~teejee2008/+archive/ubuntu/ppa/+files/conky-manager_2.3.3~132~ubuntu15.04.1.tar.xz : 9551aa73dc949708c1332a6494a775bbf2fa90a48e4a676e788556446de030ec
license    : GPL-3.0
summary    : Conky Manager
description: |
    Conky Manager is a graphical front-end for managing Conky config files. It provides options to start/stop, browse and edit Conky themes installed on the system.
rundeps    :
    - conky
    - p7zip
    - imagemagick
builddeps  :
    - vala
    - pkgconfig(gee-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(cairo)
    - pkgconfig(ImageMagick)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libsoup-2.4)
build      : |
    %patch -p1 < $pkgfiles/0001-Use-Gtk.ListStore-explicitly-due-to-new-GLib-API-GLi.patch
    %make -j1
install    : |
    %make_install
